webtalk_init -webtalk_dir C:/Users/kccistc/Desktop/Verilog_Project/20240510_8BIT_Adder_FNDdisplay/20240510_8BIT_Adder_FNDdisplay.sim/sim_1/behav/xsim/xsim.dir/tb_adder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 10 11:20:58 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "79973e57-af0f-4d49-9a44-1378bd7b95ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "936ca5c3a07d4ce9ade72e45ec310956" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1260P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "46360_KB" -context "xsim\\usage"
webtalk_transmit -clientid 722890605 -regid "" -xml C:/Users/kccistc/Desktop/Verilog_Project/20240510_8BIT_Adder_FNDdisplay/20240510_8BIT_Adder_FNDdisplay.sim/sim_1/behav/xsim/xsim.dir/tb_adder_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/kccistc/Desktop/Verilog_Project/20240510_8BIT_Adder_FNDdisplay/20240510_8BIT_Adder_FNDdisplay.sim/sim_1/behav/xsim/xsim.dir/tb_adder_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/kccistc/Desktop/Verilog_Project/20240510_8BIT_Adder_FNDdisplay/20240510_8BIT_Adder_FNDdisplay.sim/sim_1/behav/xsim/xsim.dir/tb_adder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
