#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
<<<<<<< HEAD
# Generated by Vivado on Sun May 19 14:13:41 KST 2024
=======
# Generated by Vivado on Sat May 18 03:02:11 KST 2024
>>>>>>> 31010376d39b32aadad9f9e19a18ab00f82e6334
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj tb_UART_vlog.prj"
xvlog --incr --relax -prj tb_UART_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
