#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
<<<<<<< HEAD
# Generated by Vivado on Sun May 19 14:13:41 KST 2024
=======
# Generated by Vivado on Sat May 18 03:02:12 KST 2024
>>>>>>> 31010376d39b32aadad9f9e19a18ab00f82e6334
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 06e4189988e044f7ba9865428459ecad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_UART_behav xil_defaultlib.tb_UART xil_defaultlib.glbl -log elaborate.log"
xelab -wto 06e4189988e044f7ba9865428459ecad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_UART_behav xil_defaultlib.tb_UART xil_defaultlib.glbl -log elaborate.log

