#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< HEAD
# Generated by Vivado on Sun May 19 14:10:27 KST 2024
=======
# Generated by Vivado on Sat May 18 02:40:12 KST 2024
>>>>>>> 31010376d39b32aadad9f9e19a18ab00f82e6334
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_UART_behav -key {Behavioral:sim_1:Functional:tb_UART} -tclbatch tb_UART.tcl -log simulate.log"
xsim tb_UART_behav -key {Behavioral:sim_1:Functional:tb_UART} -tclbatch tb_UART.tcl -log simulate.log

